version: '3.3'

services:
  db:
    image: mysql:latest
    volumes:
      - type: bind
        source: ./db_data
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: nymph
      MYSQL_USER: nymph
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password

  pubsub:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile-phpcli-mysqli
    volumes:
      - type: bind
        source: ./web_data
        target: /var/nymph
    command: ["./wait-for-it.sh", "db:3306", "--", "php", "/var/nymph/pubsub.php"]
    ports:
      - "8081:8080"
    environment:
      MYSQL_HOST: db:3306
      MYSQL_DATABASE: nymph
      MYSQL_USER: nymph
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password

  web:
    depends_on:
      - db
      - pubsub
    build:
      context: .
      dockerfile: Dockerfile-phpapache-mysqli
    volumes:
      - type: bind
        source: ./web_data
        target: /var/www/html
    ports:
      - "8080:80"
    environment:
      MYSQL_HOST: db:3306
      MYSQL_DATABASE: nymph
      MYSQL_USER: nymph
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      PUBSUB_HOST: pubsub:8080
    secrets:
      - db_password


secrets:
  db_password:
    file: db_password.txt
  db_root_password:
    file: db_root_password.txt
