version: '3.1'

services:
  web:
    depends_on:
      - fpm
    image: nginx:1.13
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
      - ./config/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  blob:
    image: minio/minio
    ports:
      - "8082:9000"
    volumes:
      - ./db_blob:/data
    command: ["server", "/data"]
    networks:
      - app-network
    environment:
      MINIO_ACCESS_KEY_FILE: "db_blob_access_key"
      MINIO_SECRET_KEY_FILE: "db_blob_secret_key"
    secrets:
      - db_blob_access_key
      - db_blob_secret_key

  db:
    build:
      context: ./config
      dockerfile: Dockerfile-mysql
    command: "--innodb_use_native_aio=0"
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: nymph
      MYSQL_USER: nymph
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password

  mta:
    build:
      context: ./config
      dockerfile: Dockerfile-mta
    volumes:
      - ./mail:/var/spool/postfix
    networks:
      - app-network

  pubsub:
    depends_on:
      - db
    build:
      context: ./config
      dockerfile: Dockerfile-pubsub
    volumes:
      - ./app:/app
    command: ["./wait-for-it.sh", "db:3306", "-t", "120", "--", "php", "/app/pubsub.php"]
    ports:
      - "8081:8080"
    networks:
      - app-network
    environment:
      MYSQL_HOST: db:3306
      MYSQL_DATABASE: nymph
      MYSQL_USER: nymph
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      TILMELD_SECRET_FILE: /run/secrets/tilmeld_secret
    secrets:
      - db_password
      - tilmeld_secret

  fpm:
    depends_on:
      - db
      - mta
      - pubsub
    build:
      context: ./config
      dockerfile: Dockerfile-fpm
    volumes:
      - ./app:/app
      - ./maintenance:/maintenance
    networks:
      - app-network
    environment:
      MYSQL_HOST: db:3306
      MYSQL_DATABASE: nymph
      MYSQL_USER: nymph
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      PUBSUB_HOST: pubsub:8080
      TILMELD_SECRET_FILE: /run/secrets/tilmeld_secret
      BLOB_API: s3
      BLOB_HOST: blob:9000
      BLOB_ACCESS_KEY_FILE: /run/secrets/db_blob_access_key
      BLOB_SECRET_KEY_FILE: /run/secrets/db_blob_secret_key
      # No, these aren't the same ones used on tunnelgram.com.
      WEB_PUSH_VAPID_PRIVATE_KEY: l8YS2iO3ZdEMgC6HqC6lnDARgwLXvB2TJgLDCYDmpTY
      WEB_PUSH_VAPID_PUBLIC_KEY: BMgNJ6YSV1Dv3VkazCKC004Ft33dcqscBDuvh_R3Qk98k5_nOCb-dh7r56GsRuen-_DcLS4-Bf1bcjbpTw6ELVY
      # You also need to set this in cordova/www/js/index.js
      ONESIGNAL_APP_ID: 113ebc97-79d7-4f63-9f20-045913af0a49
      ONESIGNAL_REST_API_KEY_FILE: /run/secrets/onesignal_rest_api_key
    secrets:
      - db_password
      - tilmeld_secret
      - db_blob_access_key
      - db_blob_secret_key
      - onesignal_rest_api_key

networks:
  app-network:
    driver: bridge

secrets:
  db_password:
    file: db_password.txt
  db_root_password:
    file: db_root_password.txt
  db_blob_access_key:
    file: db_blob_access_key.txt
  db_blob_secret_key:
    file: db_blob_secret_key.txt
  tilmeld_secret:
    file: tilmeld_secret.txt
  onesignal_rest_api_key:
    file: onesignal_rest_api_key.txt
